name: build

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:   [linux]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Vet & test
        run: |
          go vet ./...
          go test ./...

      - name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
        env:
          CGO_ENABLED: 0
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -trimpath -ldflags "-s -w" \
            -o scw_sd-${{ matrix.goos }}-${{ matrix.goarch }} scw_sd.go

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: scw_sd-${{ matrix.goos }}-${{ matrix.goarch }}
          path: scw_sd-${{ matrix.goos }}-${{ matrix.goarch }}
