name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Linux amd64
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o scw_sd-linux-amd64 main.go

      - name: Build macOS amd64
        run: |
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o scw_sd-darwin-amd64 main.go

      - name: Build macOS arm64
        run: |
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o scw_sd-darwin-arm64 main.go

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            scw_sd-linux-amd64
            scw_sd-darwin-amd64
            scw_sd-darwin-arm64
